site_name: MSUDocs
theme:
 name: "material"
 plugins:
  - search
  - mkdocstrings:
      module: modules  
nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md


